/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Khoa
 */

import com.application.chatboxp2p.staticdata.ListFriends;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
public class MainUI extends javax.swing.JFrame {
    
    private HashMap<Integer , JTextPane> list_chat_section = new HashMap<>(); // TEST
    private LoginUI loginUI;
    private ListFriends lf = new ListFriends();
    private static boolean first_time = true;
    private JTextPane current_text_pane;
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
    }
    public MainUI(LoginUI loginUI){
        System.out.println("CREATE MAINUI");
        this.loginUI = loginUI;
        initComponents();
        this.chat_box.setVisible(false);
        //init List Friend
        list_user.setCellRenderer(new UserRenderer());
        list_user.setModel(lf.getListModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        main_UI_pane = new javax.swing.JPanel();
        user_status_pane = new javax.swing.JPanel();
        profile_icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        add_user_but = new javax.swing.JButton();
        list_user_pane = new javax.swing.JPanel();
        find_user_field = new javax.swing.JTextField();
        find_user_but = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        list_user = new javax.swing.JList<>();
        chat_box = new javax.swing.JPanel();
        chat_pane = new javax.swing.JPanel();
        user_name_label = new javax.swing.JLabel();
        video_but = new javax.swing.JButton();
        close_conversation = new javax.swing.JButton();
        chat_section = new javax.swing.JPanel();
        text_pane = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        input_text = new javax.swing.JTextArea();
        attach_file_but = new javax.swing.JButton();
        send_mess_but = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        file_but = new javax.swing.JMenu();
        logout_but = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat Box");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(0, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSeparator1.setOpaque(true);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 10, 460));

        main_UI_pane.setBackground(new java.awt.Color(51, 204, 255));
        main_UI_pane.setOpaque(false);
        main_UI_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_status_pane.setOpaque(false);
        user_status_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profile_icon.setBackground(new java.awt.Color(0, 102, 102));
        profile_icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khoa\\OneDrive\\Documents\\NetBeansProjects\\ChatBoxP2P\\src\\main\\java\\images\\profile_icon.png")); // NOI18N
        user_status_pane.add(profile_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 80));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Chats");
        user_status_pane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 70, 80));

        add_user_but.setBackground(new java.awt.Color(0, 102, 102));
        add_user_but.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khoa\\OneDrive\\Documents\\NetBeansProjects\\ChatBoxP2P\\src\\main\\java\\images\\icons8_add_user_male_48px_1.png")); // NOI18N
        add_user_but.setBorder(null);
        add_user_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_user_butActionPerformed(evt);
            }
        });
        user_status_pane.add(add_user_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 50, -1));

        main_UI_pane.add(user_status_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 80));

        list_user_pane.setOpaque(false);

        find_user_field.setBackground(new java.awt.Color(204, 204, 204));
        find_user_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        find_user_field.setForeground(new java.awt.Color(255, 255, 255));
        find_user_field.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        find_user_field.setOpaque(false);

        find_user_but.setBackground(new java.awt.Color(0, 102, 102));
        find_user_but.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khoa\\OneDrive\\Documents\\NetBeansProjects\\ChatBoxP2P\\src\\main\\java\\images\\find_user_icon_30.png")); // NOI18N
        find_user_but.setBorderPainted(false);

        list_user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        list_user.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_userMouseClicked(evt);
            }
        });
        list_user.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                list_userValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(list_user);

        javax.swing.GroupLayout list_user_paneLayout = new javax.swing.GroupLayout(list_user_pane);
        list_user_pane.setLayout(list_user_paneLayout);
        list_user_paneLayout.setHorizontalGroup(
            list_user_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_user_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(list_user_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(list_user_paneLayout.createSequentialGroup()
                        .addComponent(find_user_field, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(find_user_but, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        list_user_paneLayout.setVerticalGroup(
            list_user_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_user_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(list_user_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(find_user_field, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(find_user_but, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))
        );

        main_UI_pane.add(list_user_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 230, 370));

        getContentPane().add(main_UI_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 460));

        chat_box.setBackground(new java.awt.Color(0, 0, 0));
        chat_box.setOpaque(false);
        chat_box.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chat_pane.setBackground(new java.awt.Color(0, 102, 102));
        chat_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_name_label.setBackground(new java.awt.Color(0, 102, 102));
        user_name_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        user_name_label.setForeground(new java.awt.Color(255, 255, 255));
        user_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_name_label.setText("Khoa");
        user_name_label.setOpaque(true);
        chat_pane.add(user_name_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 39));

        video_but.setBackground(new java.awt.Color(0, 102, 102));
        video_but.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khoa\\OneDrive\\Documents\\NetBeansProjects\\ChatBoxP2P\\src\\main\\java\\images\\video_icon.png")); // NOI18N
        video_but.setContentAreaFilled(false);
        video_but.setOpaque(true);
        chat_pane.add(video_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 50, -1));

        close_conversation.setBackground(new java.awt.Color(0, 102, 102));
        close_conversation.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khoa\\OneDrive\\Documents\\NetBeansProjects\\ChatBoxP2P\\src\\main\\java\\images\\close_conservation_icon.png")); // NOI18N
        close_conversation.setContentAreaFilled(false);
        close_conversation.setOpaque(true);
        close_conversation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_conversationActionPerformed(evt);
            }
        });
        chat_pane.add(close_conversation, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 50, -1));

        javax.swing.GroupLayout chat_sectionLayout = new javax.swing.GroupLayout(chat_section);
        chat_section.setLayout(chat_sectionLayout);
        chat_sectionLayout.setHorizontalGroup(
            chat_sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        chat_sectionLayout.setVerticalGroup(
            chat_sectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        chat_pane.add(chat_section, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 610, 370));

        chat_box.add(chat_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        text_pane.setBackground(new java.awt.Color(0, 51, 51));
        text_pane.setOpaque(false);

        input_text.setColumns(20);
        input_text.setLineWrap(true);
        input_text.setRows(5);
        input_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_textKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(input_text);

        attach_file_but.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khoa\\OneDrive\\Documents\\NetBeansProjects\\ChatBoxP2P\\src\\main\\java\\images\\attach_icon.png")); // NOI18N
        attach_file_but.setBorderPainted(false);
        attach_file_but.setContentAreaFilled(false);
        attach_file_but.setOpaque(false);

        send_mess_but.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khoa\\OneDrive\\Documents\\NetBeansProjects\\ChatBoxP2P\\src\\main\\java\\images\\send_mess_icon.png")); // NOI18N
        send_mess_but.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        send_mess_but.setBorderPainted(false);
        send_mess_but.setContentAreaFilled(false);
        send_mess_but.setOpaque(false);
        send_mess_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_mess_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout text_paneLayout = new javax.swing.GroupLayout(text_pane);
        text_pane.setLayout(text_paneLayout);
        text_paneLayout.setHorizontalGroup(
            text_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, text_paneLayout.createSequentialGroup()
                .addComponent(attach_file_but, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 540, Short.MAX_VALUE)
                .addComponent(send_mess_but))
            .addGroup(text_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, text_paneLayout.createSequentialGroup()
                    .addContainerGap(33, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );
        text_paneLayout.setVerticalGroup(
            text_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(text_paneLayout.createSequentialGroup()
                .addGroup(text_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(send_mess_but, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attach_file_but, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(text_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(text_paneLayout.createSequentialGroup()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        chat_box.add(text_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 610, 30));

        getContentPane().add(chat_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 610, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khoa\\OneDrive\\Documents\\NetBeansProjects\\ChatBoxP2P\\src\\main\\java\\images\\bg_mainUI.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        file_but.setText("File");

        logout_but.setIcon(new javax.swing.ImageIcon("C:\\Users\\Khoa\\OneDrive\\Documents\\NetBeansProjects\\ChatBoxP2P\\src\\main\\java\\images\\logout_icon.png")); // NOI18N
        logout_but.setText("Log Out");
        logout_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_butActionPerformed(evt);
            }
        });
        file_but.add(logout_but);

        jMenuBar1.add(file_but);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_butActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Are you sure?", "Log out", JOptionPane.YES_NO_OPTION) ==0)
        {
            loginUI.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logout_butActionPerformed

    private void add_user_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_user_butActionPerformed
        AddFriendUI addFriendUI = new AddFriendUI();
        addFriendUI.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        addFriendUI.setVisible(true);
    }//GEN-LAST:event_add_user_butActionPerformed

    private void list_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_userMouseClicked
        JList list = (JList)evt.getSource(); 
        if (evt.getClickCount() == 2) {
            if (first_time == true){
                chat_box.setVisible(true);
                first_time = false;
            }
            
            int index = list.locationToIndex(evt.getPoint());            
            System.out.println(index + "\n");
            if (!list_chat_section.containsKey(index))
            {
                System.out.println("Create new Chat box");
                JTextPane temp = new JTextPane();
                temp.setSize(chat_section.getSize());
                chat_section.removeAll();
                chat_section.add(temp);
                current_text_pane = temp;
                user_name_label.setText(lf.getUserByIndex(index).getName());
                chat_section.repaint();
                list_chat_section.put(index , temp);
                lf.updateStatus(index, 1);
                list_user.updateUI();
            }
            else{
                System.out.println("Open chat box " + index);
                chat_section.removeAll();
                current_text_pane = list_chat_section.get(index);
                chat_section.add(current_text_pane);
                user_name_label.setText(lf.getUserByIndex(index).getName());
                chat_section.repaint();
                lf.updateStatus(index, 1);
                list_user.updateUI();
            }
        }
    }//GEN-LAST:event_list_userMouseClicked

    private void close_conversationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_conversationActionPerformed
        
    }//GEN-LAST:event_close_conversationActionPerformed

    private void send_mess_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_mess_butActionPerformed
        sendText();
    }//GEN-LAST:event_send_mess_butActionPerformed

    private void input_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_textKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            sendText();
            evt.consume();
        }
    }//GEN-LAST:event_input_textKeyPressed

    private void list_userValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_list_userValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_list_userValueChanged
    private void sendText(){
        String text = input_text.getText();
        if (!text.equals(""))
        {
            String[] indexString = text.split(" ");
            if (indexString[0].equals("update") && indexString.length==3){
                lf.updateStatus(indexString[1] , Integer.parseInt(indexString[2]));
                list_user.updateUI();
            }
            try {
                StyledDocument doc = current_text_pane.getStyledDocument();
                Style style = current_text_pane.addStyle("myStyle", null);
                JLabel label_me = new JLabel("Me:  ");
                label_me.setFont(new java.awt.Font("Times New Roman", 1, 16));
                label_me.setForeground(new java.awt.Color(160, 28, 28));
                StyleConstants.setComponent(style, label_me);
                doc.insertString(doc.getLength(), " ", style);
                
                JTextArea textArea = new JTextArea(text);
                textArea.setLineWrap(true);
                textArea.setFont(new java.awt.Font("Times New Roman", 1, 14));
                
                StyleConstants.setComponent(style, textArea);
                doc.insertString(doc.getLength(), "\n", style);
                
            } catch (BadLocationException ex) {
                Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            input_text.setText("");
            System.out.println(text);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_user_but;
    private javax.swing.JButton attach_but;
    private javax.swing.JButton attach_but1;
    private javax.swing.JButton attach_file_but;
    private javax.swing.JPanel chat_box;
    private javax.swing.JPanel chat_pane;
    private javax.swing.JPanel chat_section;
    private javax.swing.JButton close_conversation;
    private javax.swing.JMenu file_but;
    private javax.swing.JButton find_user_but;
    private javax.swing.JTextField find_user_field;
    private javax.swing.JTextArea input_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JList<String> list_user;
    private javax.swing.JPanel list_user_pane;
    private javax.swing.JMenuItem logout_but;
    private javax.swing.JPanel main_UI_pane;
    private javax.swing.JLabel profile_icon;
    private javax.swing.JButton send_but;
    private javax.swing.JButton send_but1;
    private javax.swing.JButton send_mess_but;
    private javax.swing.JPanel text_pane;
    private javax.swing.JPanel type_section;
    private javax.swing.JPanel type_section1;
    private javax.swing.JLabel user_name_label;
    private javax.swing.JPanel user_status_pane;
    private javax.swing.JButton video_but;
    // End of variables declaration//GEN-END:variables
}
